version: '3'

services:
  redis:
    image: redis:7.0.8-bullseye
    container_name: "${REDIS_HOST}"
    volumes:
      - ./redis-data:/data
    networks:
      - portablehack-network
    environment:
      - REDIS_MAXMEMORY=8gb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    command: redis-server --bind 0.0.0.0 --requirepass ${REDIS_PASS}
    mem_limit: 8gb

  mongodb:
    image: mongo:6.0.4
    container_name: "${MONGODB_HOST}"
    volumes:
      - ./mongo-data:/data/db
      - ./mongod.conf:/etc/mongodb/mongod.conf:ro
    networks:
      - portablehack-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS}
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    command: mongod --config /etc/mongodb/mongod.conf

  iptoasn-webservice:
    build:
      context: .
      dockerfile: ./iptoasn-webservice/Dockerfile
    image: "iptoasn-webservice:1.0"
    entrypoint: /iptoasn-entrypoint.sh
    container_name: "${IPTOASN_HOST}"
    environment:
      - IPTOASN_PORT=${IPTOASN_PORT}
      - IPTOASN_DBURL=${IPTOASN_DBURL}
    networks:
      - portablehack-network

  portablehack-webservice:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: portablehack-webservice:0.1
    container_name: portablehack-webservice
    depends_on:
      - mongodb
      - redis
      - iptoasn-webservice
    ports:
      - ${LISTEN_PORT}:${LISTEN_PORT}
    volumes:
      - .:/app
    networks:
      - portablehack-network
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    entrypoint: ["python3", "/app/main.py"]

networks:
  portablehack-network:
    name: portablehack-network
    driver: bridge
